language: node_js

node_js:
  - "stable"

script:
  - npm install
  - npm test -- --detectOpenHandles
  - npm run build # Opcional, si implementas una compilación

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GH_TOKEN
  local_dir: build
  on:
    branch: gh-pages